version: "3.8"
services:
  app:
    build: .
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      - DEBUG=1
    deploy:
      resources:
        limits:
          memory: 2gb
          cpus: "0.5"
