on:
  push:
    # branches:
    #   - main
    paths:
      - .github/workflows/deploy.yaml
      - Dockerfile
      - go.*
      - "*.go"
env:
  REGISTRY: ghcr.io
  TAG: release
jobs:
  build-container:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set metadata for image
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.sha }}
            type=schedule,pattern={{date 'YYYYMMDD-HHmmss' }},prefix=at-
            type=raw,value=${{ env.TAG }}
      - name: 
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
